### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Evgen4X** [Evgen4X/Evgen4x.github.io#1]
# TODO list
- [ ] **Add settings** in TexasHoldem
- [x] Add number of guesses in wordles
- [x] Change `question-icon.png`
- [x] Change `main-icon.jpg` to `.png`
- [ ] ***Write texas holdem***
- [x] Add more things?
- [x] Include other best cards in FOAK, TOAK, TP, P
- [x] Polynomial multiplication: (a+b)(a-b) != (a+b)(-b+a) bug
- [ ] Polynomial multiplication: (a+b+c)^3=4abc+cba+bac (+...) bug
- [x] Fix CSS
- [x] FIX THAT DAMN CSS
- [x] Wordles/verticalle: double letters in the answer correct coloring fix
- [x] Add more letter option to verticalle
- [x] Pong: add powerups: smaller ball, big/small platform, second ball, ball redirection, faster/slower player movement speed
- [ ] Pong: add PvE, difficulties: easy (bot thinks slowly, sometimes makes mistakes), medium (mod things quite fast and barely makes mistakes), hard (bot knows where the ball is going to go), insane (bot knows where the ball is going, returns to the middle after hit to get the best position, and tries to collect only good powerups)
- [x] Fix points in pong
- [ ] add db generator
- [ ] add minesweeper
- [ ] add snake
- [x] add pong win screen
- [ ] Main screen add transparency to icons when highlighted
